{
 "title": "ODPF Dagger Timeboard open source",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values from \"jobmanager_numRegisteredTaskManagers\" with key=\"host\""
   },
   {
    "name": "Jobs",
    "label": "Flink Jobs",
    "query": "show tag values from \"jobmanager_job_uptime\" with key=\"job_name\"  where host = '$cluster'"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of the job on the cluster:         \n*Stopped*: Current status is stopped     \n*Started*: The dagger has restarted once or more during the selected time interval\n*Running*: The dagger is running fine for the duration selected",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "de.dagger_job.uptime",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime since last restart",
   "type": "stat",
   "description": "The time that the job ran/running since the last restart",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jobmanager_job_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Sink",
   "type": "stat",
   "description": "The configured sink type for dagger",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_sink_type_value",
     "query": "select last(\"sink_type\") as output_sink from (select \"sink_type\",\"value\" from \"taskmanager_job_task_operator_sink_type_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Full restarts",
   "type": "stat",
   "description": "The total number of full restarts since this job was submitted",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jobmanager_job_fullRestarts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Total downtime",
   "type": "stat",
   "description": "For jobs currently in a restarting situation, the time elapsed during this outage.\nReturns 0 for running jobs",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_downtime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Max kafka consumer lag",
   "type": "graph",
   "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers. This is for each task.           \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index : $tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_records-lag-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Late Records Dropped per 5 minutes",
   "type": "graph",
   "description": "The number of records a task has dropped due to arriving late.             \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task $tag_subtask_index",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_numLateRecordsDropped",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Rate - All Stages",
   "type": "graph",
   "description": "This gives an idea of data flow through tasks.    \nInput: The number of records a task receives per second.\nOutput: The number of records a task sends per second.                           \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Task ($tag_subtask_index): Input",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_numRecordsInPerSecond",
     "query": "SELECT mean(\"rate\") FROM \"taskmanager_job_task_operator_numRecordsInPerSecond\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"subtask_index\" fill(0)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "Task ($tag_subtask_index): Output",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_numRecordsOutPerSecond",
     "query": "SELECT mean(\"rate\") FROM \"taskmanager_job_task_operator_numRecordsOutPerSecond\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"subtask_index\" fill(0)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Kafka Consumer Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Assigned partitions",
   "type": "graph",
   "description": "Consumer Group Metrics: The number of partitions currently assigned to this consumer (per source task).      \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_assigned-partitions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Number of Request /second",
   "type": "graph",
   "description": "Global Request Metrics: The average number of requests sent per second per source task.       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_request-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Consumed Rate /second",
   "type": "graph",
   "description": "The average number of records consumed per second per source task (a task that is responsible for reading from Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_records-consumed-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate /second",
   "type": "graph",
   "description": "The average number of bytes consumed per second per source task (part of the job responsible for consuming from Kafka) .          \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_bytes-consumed-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Fetch Rate /second",
   "type": "graph",
   "description": "Fetch Metrics: The number of fetch requests per second per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_fetch-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Fetch Latency",
   "type": "graph",
   "description": "Fetch Metrics: The max time taken for a fetch request per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_fetch-latency-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Fetch Latency",
   "type": "graph",
   "description": "The average time taken for a fetch request per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_fetch-latency-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Fetch Size",
   "type": "graph",
   "description": "The average number of bytes fetched per request per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_fetch-size-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Fetch Size",
   "type": "graph",
   "description": "The max number of bytes fetched per request per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_fetch-size-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Commit Rate /second",
   "type": "graph",
   "description": "The number of commit calls per second per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_commit-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Active Connections Count",
   "type": "graph",
   "description": "The current number of active connections per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_connection-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "New Connections Creation Rate /second",
   "type": "graph",
   "description": "New connections established per second in the window per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_connection-creation-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections Close Rate /second",
   "type": "graph",
   "description": "Connections closed per second in the window per\nsource task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_connection-close-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Outgoing Byte Rate/second",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second to all servers per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_outgoing-byte-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Sync rate /second",
   "type": "graph",
   "description": "The number of group syncs per second per source task(part of the job responsible for consuming from Kafka) . Group synchronization is the second and last phase of the rebalance protocol. Similar to join-rate, a large value indicates group instability .     \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_sync-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "graph",
   "description": "The average time taken for a commit request per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_commit-latency-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Commit Latency",
   "type": "graph",
   "description": " The max time taken for a commit request per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_commit-latency-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Network IO rate /second",
   "type": "graph",
   "description": "The average number of network operations (reads or writes) on all connections per second per source task(part of the job responsible for consuming from Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaConsumer_network-io-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Input Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Input Topics",
   "type": "table-old",
   "description": "The name of topics from which the dagger is consuming",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "input_topic" ], "type": "tag" }
     ],
     "measurement": "taskmanager_job_task_operator_input_topic_value",
     "query": "select DISTINCT(\"input_topic\") as topic_names from (select \"input_topic\",\"value\" from \"taskmanager_job_task_operator_input_topic_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Protos",
   "type": "table-old",
   "description": "The protos which the dagger is using to consume from topics",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"input_proto\") as proto_names from (select \"input_proto\",\"value\" from \"taskmanager_job_task_operator_input_proto_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Streams",
   "type": "table-old",
   "description": "The Kafka stream where the input topic belongs",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"input_stream\") as input_streams from (select \"input_stream\",\"value\" from \"taskmanager_job_task_operator_input_stream_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "fatal exceptions",
   "type": "graph",
   "description": "List of exceptions thrown by dagger which will result in restarting the job",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_fatal.exception]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_difference(mean(\"count\")) FROM \"taskmanager_job_task_operator_fatal_exception_value\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"fatal.exception\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "warnings",
   "type": "graph",
   "description": "List of warnings coming in dagger(not resulting in job restart)",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_non.fatal.exception]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_difference(mean(\"count\")) FROM \"taskmanager_job_task_operator_non_fatal_exception_value\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"non.fatal.exception\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Late Record Drops",
   "type": "graph",
   "description": "The number of records that could not be pushed to InfluxDB due to out of bound retention period.\nThis is a counter so is incremental for a given job.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_influx_late_records_dropped_value",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Avg Request Latency",
   "type": "graph",
   "description": "Avg time between when send() was called by the producer until the producer receives a response from the broker per source task(part of the job responsible for producing to Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_request-latency-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Request Latency",
   "type": "graph",
   "description": "Max time between when send() was called by the producer until it receives a response from the broker per source task(part of the job responsible for producing to Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_request-latency-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Produce Request Rate /second",
   "type": "graph",
   "description": "The average number of requests sent per second per source task(part of the job responsible for producing to Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_request-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Produce Response Rate /second",
   "type": "graph",
   "description": "The average number of responses received per second per source task(part of the job responsible for producing to Kafka)                \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_response-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Record Send Rate /second",
   "type": "graph",
   "description": "The average number of records sent for a topic per second per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_record-send-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Records Per Request",
   "type": "graph",
   "description": "The average number of records in each request per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_records-per-request-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Producer Active Connection Count",
   "type": "graph",
   "description": "The current number of active connections per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_connection-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Producer Network IO rate /second",
   "type": "graph",
   "description": "The average number of network operations (reads or writes) on all connections per second per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_network-io-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Record Size",
   "type": "graph",
   "description": "The average record size per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_record-size-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Record Size",
   "type": "graph",
   "description": "The maximum record size per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_record-size-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Record Send Error Rate /second",
   "type": "graph",
   "description": "The average number of records sent that resulted in errors for a topic per-second per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_record-error-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "graph",
   "description": "Number of in-flight requests awaiting a response per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_requests-in-flight",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Record Queue Time",
   "type": "graph",
   "description": "The average time in milliseconds record batches spent in the record accumulator per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_record-queue-time-avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Record Queue Time",
   "type": "graph",
   "description": "The maximum time in milliseconds record batches spent in the record accumulator per source task (a task that is responsible for producing to Kafka).       \n1 <= Number of task <=  parallelism",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Task: $tag_subtask_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subtask_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_KafkaProducer_record-queue-time-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Output Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Output Sink",
   "type": "table-old",
   "description": "The configured sink type for dagger",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 113 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"sink_type\") as output_sink from (select \"sink_type\",\"value\" from \"taskmanager_job_task_operator_sink_type_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Topic",
   "type": "table-old",
   "description": "The name of the topic to which the dagger is producing. This is applicable for only Kafka sink daggers",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 113 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"output_topic\") as output_topic_names from (select \"output_topic\",\"value\" from \"taskmanager_job_task_operator_output_topic_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Proto",
   "type": "table-old",
   "description": "The proto which the dagger is using to produce to the topic. This is applicable for only Kafka sink daggers",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 113 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"output_proto\") as output_proto from (select \"output_proto\",\"value\" from \"taskmanager_job_task_operator_output_proto_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Stream",
   "type": "table-old",
   "description": "The Kafka stream where the output topic belongs.\nThis is applicable for only Kafka sink daggers, at present this info is not available.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 113 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"output_stream\") as output_stream from (select \"output_stream\",\"value\" from \"taskmanager_job_task_operator_output_stream_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "UDFs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Names",
   "type": "table-old",
   "description": "List of UDFs used in the dagger query",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_udf_dart_gcs_file_size",
     "query": "select DISTINCT(\"udf\") as \"UDF Name\" from (select \"udf\",\"value\" from \"taskmanager_job_task_operator_udf_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dart: Metrics",
   "type": "table-old",
   "description": "Path and Size of the file used in DART from GCS",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"value\") as \"FileSizeInKB\" from (select \"DartPath\",\"value\" from \"taskmanager_job_task_operator_dartpath_dart_gcs_file_size\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/ ) group by DartPath",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dart: Cache Hit",
   "type": "graph",
   "description": "The average rate of the cache hit when using DARTs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task ($tag_subtask_index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_udf_dart_cache_fetch_success",
     "query": "SELECT mean(\"rate\") FROM \"taskmanager_job_task_operator_udf_dart_cache_fetch_success\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"subtask_index\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dart: Cache Miss",
   "type": "graph",
   "description": "The average rate of the cache miss when using DARTs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task ($tag_subtask_index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") FROM \"taskmanager_job_task_operator_udf_dart_cache_fetch_failure\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"subtask_index\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dart: GCS Fetch Success",
   "type": "graph",
   "description": "The average rate of the successful GCS fetch when using DARTs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task ($tag_subtask_index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") FROM \"taskmanager_job_task_operator_udf_dart_gcs_bucket_fetch_success\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"subtask_index\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dart: GCS Fetch Failure",
   "type": "graph",
   "description": "The average rate of the failure GCS fetch when using DARTs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task ($tag_subtask_index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") FROM \"taskmanager_job_task_operator_udf_dart_gcs_bucket_fetch_failure\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m), \"subtask_index\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "Pre Processors Names",
   "type": "table-old",
   "description": "List of Pre Processors applied on the dagger.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"pre_processor_type\") as pre_processors from (select \"pre_processor_type\",\"value\" from \"taskmanager_job_task_operator_pre_processor_type_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Post Processors Names",
   "type": "table-old",
   "description": "List of Post Processors applied on the dagger",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 149 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select DISTINCT(\"post_processor_type\") as post_processors from (select \"post_processor_type\",\"value\" from \"taskmanager_job_task_operator_post_processor_type_value\" WHERE $timeFilter AND  \"job_name\" =~ /^$Jobs$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total External Calls Rate",
   "type": "graph",
   "description": "Total calls to the external source per minute. which can be either one of an HTTP endpoint / ElasticSearch / PostgresDB, based on post processor type.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Total External Calls Rate ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_total_external_calls",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Success Response Time",
   "type": "graph",
   "description": "Time taken by the external client to send back the response to daggers, in case of a successful event.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 155 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p50 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_success_response_time",
     "query": "SELECT sum(\"value\") FROM \"external.source.http.successResponseTime.p50\" WHERE (\"flink_cluster\" =~ /^$cluster$/ AND \"job_name\" =~ /^$dagger$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_success_response_time",
     "query": "SELECT sum(\"value\") FROM \"external.source.http.successResponseTime.p95\" WHERE (\"flink_cluster\" =~ /^$cluster$/ AND \"job_name\" =~ /^$dagger$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_success_response_time",
     "query": "SELECT sum(\"value\") FROM \"external.source.http.successResponseTime.p99\" WHERE (\"flink_cluster\" =~ /^$cluster$/ AND \"job_name\" =~ /^$dagger$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_success_response_time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "description": "Number of Successful events received per minute",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 155 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "success response rate ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_success_response",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Response Time",
   "type": "graph",
   "description": "Time taken by the external client to send back the response to daggers, in case of a failed event.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p50 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failure_response_time",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failure_response_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failure_response_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failure_response_time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Failure Requests Rate",
   "type": "graph",
   "description": "Number of failed events received per minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Total Failure Rate ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_total_failures",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Rate on 404 Response",
   "type": "graph",
   "description": "Number of failed events received per minute with response code 404 (Not Found)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Failure Rate on 404 ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failures_code404",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Rate on 4XX Response",
   "type": "graph",
   "description": "Number of failed events received per minute with response code 4XX , other than 404",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Failure Rate on 4XX ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failures_code4XX",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Rate on 5XX HTTP calls",
   "type": "graph",
   "description": "Number of failed events received per minute with response code 5XX",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 171 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Failures Rate on 5XX ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failures_code5XX",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Timeouts Rate",
   "type": "graph",
   "description": "Number of timeouts per minute from external source, which can be either one of an HTTP endpoint / ElasticSearch / PostgresDB, based on post processor type",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 171 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Timeouts Rate ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_timeouts",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Close Connection On Client Rate",
   "type": "graph",
   "description": "Number of times connection to the external client is closed per minute",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 179 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Close Connection On Client Rate ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_close_connection_on_external_client",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failures Rate On Reading Path",
   "type": "graph",
   "description": "Number of failed events per minute caused while reading path configured in post processor  config",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 179 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Failures Rate On Reading Path ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_failures_on_reading_path",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Rate On Other Errors",
   "type": "graph",
   "description": "Failure rate due to an error other than the ones covered above",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 179 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Other Failures Count ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_other_errors",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Rate On Empty Request",
   "type": "graph",
   "description": "Failure rate when all the values of the request variable are empty or empty endpoints.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "Empty Request Variables Values ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_empty_input",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "Empty Endpoint ($tag_source_metricId)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "source_metricId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_source_metricId_empty_endpoint",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Records dropped",
   "type": "graph",
   "description": "Failure rate when all the values of the request variable are empty or empty endpoints.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "alias": "$tag_operator_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "operator_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_filtered_invalid_records",
     "query": "SELECT sum(\"count\") FROM \"taskmanager_job_task_operator_InvalidRecordFilterTransformer_filtered_invalid_records\" WHERE (\"job_name\" =~ /^$Jobs$/) AND $timeFilter GROUP BY time(1m),table_name fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Longbow Reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 } },
  {
   "title": "Rate of successful reads",
   "type": "graph",
   "description": "Number of successfully read documents from Big Table per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "docs per second",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_reader_success_on_read_document",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Successful read time",
   "type": "graph",
   "description": "Time taken by the Big Table to send back the response to daggers, in case of a successful read event.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 194 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p50",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "operator_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_reader_success_on_read_document_response_time",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_reader_success_on_read_document_response_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_reader_success_on_read_document_response_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_reader_success_on_read_document_response_time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Successful reads",
   "type": "graph",
   "description": "Number of successfully read documents from Big Table per 10s",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_reader_success_on_read_document",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Docs read per scan",
   "type": "graph",
   "description": "Number of documents read from Big Table per scan.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "p50",
     "measurement": "taskmanager_job_task_operator_longbow_reader_documents_read_per_scan",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95",
     "measurement": "taskmanager_job_task_operator_longbow_reader_documents_read_per_scan",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99",
     "measurement": "taskmanager_job_task_operator_longbow_reader_documents_read_per_scan",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean",
     "measurement": "taskmanager_job_task_operator_longbow_reader_documents_read_per_scan",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Missed records",
   "type": "graph",
   "description": "Indicates those events for which there is either no data or invalid data in the Big Table.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_reader_failed_to_read_last_record",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed to read documents",
   "type": "graph",
   "description": "Number of failures in reading documents.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_reader_failed_on_read_document",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Time taken for failed documents",
   "type": "graph",
   "description": "Time taken by the Big Table to send back the response to daggers, in case of a failed read event.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p50",
     "measurement": "taskmanager_job_task_operator_longbow_reader_failed_on_read_document_response_time",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95",
     "measurement": "taskmanager_job_task_operator_longbow_reader_failed_on_read_document_response_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99",
     "measurement": "taskmanager_job_task_operator_longbow_reader_failed_on_read_document_response_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean",
     "measurement": "taskmanager_job_task_operator_longbow_reader_failed_on_read_document_response_time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "graph",
   "description": "Number of timeouts from Big Table while reading from it.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_reader_timeouts_on_reader",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Close Connection",
   "type": "graph",
   "description": "Number of times connection to the Big Table is closed while reading from it.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_reader_close_connection_on_reader",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Longbow Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Rate of successful writes",
   "type": "graph",
   "description": "Number of successful writes to Big Table per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "docs per second",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_write_document",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Successful write time",
   "type": "graph",
   "description": "Time taken by the Big Table to send back the response to daggers, in case of a successful write event.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 219 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p50",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_write_document_response_time",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_write_document_response_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_write_document_response_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_write_document_response_time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Success document writes",
   "type": "graph",
   "description": "The number of successful document writes to Big Table per 10s.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_write_document",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed to write documents",
   "type": "graph",
   "description": "Number of failures in writing documents to Big Table.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_writer_failed_on_write_document",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Time taken for failed documents",
   "type": "graph",
   "description": "Time taken by the Big Table to send back the response to daggers, in case of a failed write event.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 227 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p50",
     "measurement": "taskmanager_job_task_operator_longbow_writer_failed_on_write_document_response_time",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p95",
     "measurement": "taskmanager_job_task_operator_longbow_writer_failed_on_write_document_response_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "p99",
     "measurement": "taskmanager_job_task_operator_longbow_writer_failed_on_write_document_response_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "mean",
     "measurement": "taskmanager_job_task_operator_longbow_writer_failed_on_write_document_response_time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "graph",
   "description": "Number of timeouts from Big Table while writing to it.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_writer_timeouts_on_writer",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Close connection",
   "type": "graph",
   "description": "Number of times connection to the Big Table is closed while writing to it.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "taskmanager_job_task_operator_longbow_writer_close_connection_on_writer",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  {
   "title": "Create bigtable",
   "type": "graph",
   "description": "Indicates whether a table was created successfully in Big Table or not.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "failed count",
     "measurement": "taskmanager_job_task_operator_longbow_writer_failed_on_create_bigtable",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    },
    {
     "alias": "success count",
     "measurement": "taskmanager_job_task_operator_longbow_writer_success_on_create_bigtable",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" }
     ]
    }
   ]
  },
  { "title": "Checkpointing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 } },
  {
   "title": "Number of completed checkpoints",
   "type": "stat",
   "description": "Checkpoints successfully completed by the job. With time the number of checkpoints will increase",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_numberOfCompletedCheckpoints",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of failed checkpoints",
   "type": "graph",
   "description": "The number of failed checkpoints. ",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_numberOfFailedCheckpoints",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Last checkpoint duration in sec",
   "type": "graph",
   "description": "Last checkpoint duration in sec",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 244 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Last checkpoint duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_lastCheckpointDuration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Last checkpoint size",
   "type": "stat",
   "description": "The total size of the last checkpoint",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_lastCheckpointSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=~", "value": "/^$Jobs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Parquet Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Row Deserialization Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "reader_row_deserialization_time_99_percentile{ job_id=\"$dagger_job\"}",
     "legendFormat": "99p: {{host}}"
    },
    {
     "expr": "reader_row_deserialization_time_95_percentile{ job_id=\"$dagger_job\"}",
     "legendFormat": "95p: {{host}}"
    },
    {
     "expr": "reader_row_deserialization_time_50_percentile{ job_id=\"$dagger_job\"}",
     "legendFormat": "50p: {{host}}"
    },
    {
     "expr": "reader_row_deserialization_time_mean{ job_id=\"$dagger_job\"}",
     "legendFormat": "mean:{{host}}"
    }
   ]
  },
  {
   "title": "Rows Emitted By Source Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reader_rows_emitted_value{job_id=\"$dagger_job\"}[1m])",
     "legendFormat": "TaskManager: {{host}}"
    }
   ]
  },
  {
   "title": "Parquet Record Read Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "reader_row_read_time_99_percentile{job_id=\"$dagger_job\"}",
     "legendFormat": "99p:{{host}}"
    },
    {
     "expr": "reader_row_read_time_95_percentile{job_id=\"$dagger_job\"}",
     "legendFormat": "95p:{{host}}"
    },
    {
     "expr": "reader_row_read_time_50_percentile{job_id=\"$dagger_job\"}",
     "legendFormat": "50p:{{host}}"
    },
    {
     "expr": "reader_row_read_time_mean{job_id=\"$dagger_job\"}",
     "legendFormat": "mean:{{host}}"
    }
   ]
  },
  {
   "title": "Total File Splits Discovered",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_splits_discovered_value{job_id=\"$dagger_job\"}"
    }
   ]
  },
  {
   "title": "Total File Splits To Be Processed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_splits_recorded_value{job_id=\"$dagger_job\"}"
    }
   ]
  },
  {
   "title": "File Splits Remaining For Processing",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splits_awaiting_assignment_value{job_id=\"$dagger_job\"}",
     "legendFormat": "JobManager: {{host}}"
    }
   ]
  },
  {
   "title": "Readers Created Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(reader_created_value{job_id=\"$dagger_job\"}[1m])",
     "legendFormat": "TaskManager: {{host}}"
    }
   ]
  },
  {
   "title": "Readers Closed Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(reader_closed_value{job_id=\"$dagger_job\"}[1m])",
     "legendFormat": "taskManager: {{host}}"
    }
   ]
  }
 ]
}